[package]
name = "client"
version = "0.1.0"
authors = ["Andrew Dona-Couch <signal-rs@andrewcou.ch>"]

[dependencies]
capnp = "0.8"
capnp-rpc = "0.8"
futures = "0.1"
rand = "0.7.3"
rand_core = "0.5.1"
rand_chacha = "0.2.2"
sha2 = "0.7"
tokio = "0.1"

double-ratchet = { path = "../double-ratchet" }
signal-common = { path = "../signal-common" }
x3dh = { path = "../x3dh" }

[build-dependencies]
capnpc = "0.8"
