[package]
name = "double-ratchet"
version = "0.1.0"
authors = ["Andrew Dona-Couch <signal-rs@andrewcou.ch>"]

[dependencies]
aes = "0.3.2"
block-modes = "0.2.0"
curve25519-dalek = "1"
ed25519-dalek = "1.0.0-pre.1"
orion = "0.13"
rand = "0.7.3"
rand_core = "0.5.1"
sha2 = "0.7"

signal-common = { path = "../signal-common" }

[dependencies.x25519-dalek]
version = "0.5"
default-features = false
features = ["std", "u64_backend"]
